In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
Train_data=pd.read_excel('Data_Train.xlsx')  ## Training Data


In [3]:
Train_data.head()

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897  
1    05:50         13:15   7h 25m     2 stops         No info   7662  
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882  
3    18:05         23:30   5h 25m      1 stop         No info   6218  
4    16:50         21:35   4h 45m      1 stop         No info  13302

In [4]:
Train_data.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [5]:
Train_data.isnull().sum()  ## Total count of the NaNs in that particular columns

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [6]:
Train_data_copy=Train_data.copy(deep=True)
Train_data=Train_data.dropna()

In [7]:
Train_data.isnull().sum()   ## Removed all null values by dropping the NaN, becuz we have only one NaN value

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

# Splitting the Date time column to new features as Day, Month,Year


In [8]:
Train_data['Journey_Day']=pd.to_datetime(Train_data['Date_of_Journey'], format='%d/%m/%Y').dt.day
Train_data.head()      ## Adding day column

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  \
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897   
1    05:50         13:15   7h 25m     2 stops         No info   7662   
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882   
3    18:05         23:30   5h 25m      1 stop         No info   6218   
4    16:50         21:35   4h 45m      1 stop         No info  13302   

   Journey_Day  
0           24  
1            1  
2            9  
3           12  
4            1

In [9]:
Train_data['Journey_Month']=pd.to_datetime(Train_data['Date_of_Journey'],format='%d/%m/%Y').dt.month
Train_data.head()    ## Adding month column

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  \
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897   
1    05:50         13:15   7h 25m     2 stops         No info   7662   
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882   
3    18:05         23:30   5h 25m      1 stop         No info   6218   
4    16:50         21:35   4h 45m      1 stop         No info  13302   

   Journey_Day  Journey_Month  
0           24              3  
1            1              5  
2            9              6  
3           12              5  
4            1              3

# Lets Read the Test Data as well and make the changes

In [10]:
Test_data=pd.read_excel('Test_set.xlsx')

In [11]:
Test_data.head()

Airline Date_of_Journey    Source Destination            Route  \
0        Jet Airways       6/06/2019     Delhi      Cochin  DEL → BOM → COK   
1             IndiGo      12/05/2019   Kolkata    Banglore  CCU → MAA → BLR   
2        Jet Airways      21/05/2019     Delhi      Cochin  DEL → BOM → COK   
3  Multiple carriers      21/05/2019     Delhi      Cochin  DEL → BOM → COK   
4           Air Asia      24/06/2019  Banglore       Delhi        BLR → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops              Additional_Info  
0    17:30  04:25 07 Jun  10h 55m      1 stop                      No info  
1    06:20         10:20       4h      1 stop                      No info  
2    19:15  19:00 22 May  23h 45m      1 stop  In-flight meal not included  
3    08:00         21:00      13h      1 stop                      No info  
4    23:55  02:45 25 Jun   2h 50m    non-stop                      No info

In [12]:
## lets check for the null values
Test_data.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
dtype: int64

In [13]:
## No nul values as such so will proceed with further steps..
## Lests Change the date time column
Test_data['Journey_Month']=pd.to_datetime(Test_data['Date_of_Journey'],format='%d/%m/%Y').dt.month
Test_data['Journey_Day']=pd.to_datetime(Test_data['Date_of_Journey'],format='%d/%m/%Y').dt.day
Test_data.head()

Airline Date_of_Journey    Source Destination            Route  \
0        Jet Airways       6/06/2019     Delhi      Cochin  DEL → BOM → COK   
1             IndiGo      12/05/2019   Kolkata    Banglore  CCU → MAA → BLR   
2        Jet Airways      21/05/2019     Delhi      Cochin  DEL → BOM → COK   
3  Multiple carriers      21/05/2019     Delhi      Cochin  DEL → BOM → COK   
4           Air Asia      24/06/2019  Banglore       Delhi        BLR → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops              Additional_Info  \
0    17:30  04:25 07 Jun  10h 55m      1 stop                      No info   
1    06:20         10:20       4h      1 stop                      No info   
2    19:15  19:00 22 May  23h 45m      1 stop  In-flight meal not included   
3    08:00         21:00      13h      1 stop                      No info   
4    23:55  02:45 25 Jun   2h 50m    non-stop                      No info   

   Journey_Month  Journey_Day  
0              6            6  
1              5           12  
2              5           21  
3              5           21  
4              6           24

In [15]:
## Removing the column
Train_data.drop(labels='Date_of_Journey',axis=1,inplace=True)
Test_data.drop(labels='Date_of_Journey',axis=1,inplace=True)    


In [19]:
Train_data.head() ## Dataset after removing the Date_of_journey column
Test_data.head()

Airline    Source Destination            Route Dep_Time  \
0        Jet Airways     Delhi      Cochin  DEL → BOM → COK    17:30   
1             IndiGo   Kolkata    Banglore  CCU → MAA → BLR    06:20   
2        Jet Airways     Delhi      Cochin  DEL → BOM → COK    19:15   
3  Multiple carriers     Delhi      Cochin  DEL → BOM → COK    08:00   
4           Air Asia  Banglore       Delhi        BLR → DEL    23:55   

   Arrival_Time Duration Total_Stops              Additional_Info  \
0  04:25 07 Jun  10h 55m      1 stop                      No info   
1         10:20       4h      1 stop                      No info   
2  19:00 22 May  23h 45m      1 stop  In-flight meal not included   
3         21:00      13h      1 stop                      No info   
4  02:45 25 Jun   2h 50m    non-stop                      No info   

   Journey_Month  Journey_Day  
0              6            6  
1              5           12  
2              5           21  
3              5           21  
4              6           24

In [20]:
#Our duration column had time written in this format 2h 50m . 
#To help machine learning algorithm derive useful insights, we will convert this text into numeric.


duration = list(Train_data['Duration'])


for i in range(len(duration)) :
    if len(duration[i].split()) != 2: 
        if 'h' in duration[i] :
            duration[i] = duration[i].strip() + ' 0m'
        elif 'm' in duration[i] :
            duration[i] = '0h {}'.format(duration[i].strip())

dur_hours = []
dur_minutes = []  

for i in range(len(duration)) :
    dur_hours.append(int(duration[i].split()[0][:-1])) #for examole if duration is 49 mintutes 4 sec then it will reflect like 
    dur_minutes.append(int(duration[i].split()[1][:-1]))#0:49:4 and if 2 hours 10 seconds then it will reflect like 2:0:10
    
Train_data['Duration_hours'] = dur_hours
Train_data['Duration_minutes'] =dur_minutes

Train_data.drop(labels = 'Duration', axis = 1, inplace = True) # dropping the original duration column from training set


# Test Set(applyig same code to convert 'Duration' to 'Duration _Hours' and 'Duration_Minutes')
#2h 50m
durationT = list(Test_data['Duration'])

for i in range(len(durationT)) :
    if len(durationT[i].split()[0]) != 2:       
        if 'h' in durationT[i] :
            durationT[i] = durationT[i].strip() + ' 0m'
        elif 'm' in durationT[i] :
            durationT[i] = '0h {}'.format(durationT[i].strip())
            
dur_hours = []
dur_minutes = []  

for i in range(len(durationT)) :
    #print(durationT[i].split())
    dur_hours.append(int(durationT[i].split()[0][:-1]))
    if(len(durationT[i].split())>1):
        dur_minutes.append(int(durationT[i].split()[1][:-1]))
    else:
        dur_minutes.append(int(0))
  
    
Test_data['Duration_hours'] = dur_hours
Test_data['Duration_minutes'] = dur_minutes

Test_data.drop(labels = 'Duration', axis = 1, inplace = True) #  dropping the original duration column from training set

In [22]:
Train_data.head(2)

Airline    Source Destination                  Route Dep_Time  \
0     IndiGo  Banglore   New Delhi              BLR → DEL    22:20   
1  Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR    05:50   

   Arrival_Time Total_Stops Additional_Info  Price  Journey_Day  \
0  01:10 22 Mar    non-stop         No info   3897           24   
1         13:15     2 stops         No info   7662            1   

   Journey_Month  Duration_hours  Duration_minutes  
0              3               2                50  
1              5               7                25

In [25]:
Train_data['Dep_Hour']=pd.to_datetime(Train_data['Dep_Time']).dt.hour
Train_data['Dep_min']=pd.to_datetime(Train_data['Dep_Time']).dt.minute
Train_data.head(1)

Airline    Source Destination      Route Dep_Time  Arrival_Time Total_Stops  \
0  IndiGo  Banglore   New Delhi  BLR → DEL    22:20  01:10 22 Mar    non-stop   

  Additional_Info  Price  Journey_Day  Journey_Month  Duration_hours  \
0         No info   3897           24              3               2   

   Duration_minutes  Dep_Hour  Dep_min  
0                50        22       20

In [26]:
## Lets drop Dep_time
Train_data.drop(labels='Dep_Time',axis=1,inplace=True)

In [27]:
Train_data.head(1)

Airline    Source Destination      Route  Arrival_Time Total_Stops  \
0  IndiGo  Banglore   New Delhi  BLR → DEL  01:10 22 Mar    non-stop   

  Additional_Info  Price  Journey_Day  Journey_Month  Duration_hours  \
0         No info   3897           24              3               2   

   Duration_minutes  Dep_Hour  Dep_min  
0                50        22       20

In [ ]:
#Converting 'Arr_Time' to 'Arr_Time_hour' and 'Arr_time_Minutes' and dropping the original column
Train_data['Arr_Time_Hour'] = pd.to_datetime(Train_data.Arrival_Time).dt.hour
Train_data['Arr_Time_Minutes'] = pd.to_datetime(Train_data.Arrival_Time).dt.minute

Train_data.drop(labels = 'Arrival_Time', axis = 1, inplace = True)
Train_data.head(1) # cheking the training set after transformation

In [30]:
Train_data.head(1)

Airline    Source Destination      Route Total_Stops Additional_Info  Price  \
0  IndiGo  Banglore   New Delhi  BLR → DEL    non-stop         No info   3897   

   Journey_Day  Journey_Month  Duration_hours  Duration_minutes  Dep_Hour  \
0           24              3               2                50        22   

   Dep_min  Arr_Time_Hour  Arr_Time_Minutes  
0       20              1                10

In [39]:
y_train=Train_data.iloc[:,6].values  ## Dependent Features

In [40]:
X_train=Train_data.iloc[:,Train_data.columns!='Price'].values   ## independent features

In [41]:
X_test=Test_data.iloc[:,:].values

In [42]:
# From the info above it could be observed that many colmns are of object type. So, converting those categorical columns to numerical columns
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
l2=LabelEncoder()



# Lets Do for the Training Dataset


In [43]:
X_train[:,0] = l1.fit_transform(X_train[:,0])
X_train

array([[3, 'Banglore', 'New Delhi', ..., 20, 1, 10],
       [1, 'Kolkata', 'Banglore', ..., 50, 13, 15],
       [4, 'Delhi', 'Cochin', ..., 25, 4, 25],
       ...,
       [4, 'Banglore', 'Delhi', ..., 20, 11, 20],
       [10, 'Banglore', 'New Delhi', ..., 30, 14, 10],
       [1, 'Delhi', 'Cochin', ..., 55, 19, 15]], dtype=object)

In [45]:
X_train[:,1] = l1.fit_transform(X_train[:,1])
X_train

array([[3, 0, 'New Delhi', ..., 20, 1, 10],
       [1, 3, 'Banglore', ..., 50, 13, 15],
       [4, 2, 'Cochin', ..., 25, 4, 25],
       ...,
       [4, 0, 'Delhi', ..., 20, 11, 20],
       [10, 0, 'New Delhi', ..., 30, 14, 10],
       [1, 2, 'Cochin', ..., 55, 19, 15]], dtype=object)

In [46]:
X_train[:,2] = l1.fit_transform(X_train[:,2])
X_train

array([[3, 0, 5, ..., 20, 1, 10],
       [1, 3, 0, ..., 50, 13, 15],
       [4, 2, 1, ..., 25, 4, 25],
       ...,
       [4, 0, 2, ..., 20, 11, 20],
       [10, 0, 5, ..., 30, 14, 10],
       [1, 2, 1, ..., 55, 19, 15]], dtype=object)

# On Testing Dataset

In [47]:
X_test[:,0] = l2.fit_transform(X_test[:,0])

X_test[:,1] = l2.fit_transform(X_test[:,1])

X_test[:,2] = l2.fit_transform(X_test[:,2])

X_test[:,3] = l2.fit_transform(X_test[:,3])

X_test[:,4] = l2.fit_transform(X_test[:,4])

X_test[:,5] = l2.fit_transform(X_test[:,5])
X_test

array([[4, 2, 1, ..., 6, 10, 55],
       [3, 3, 0, ..., 12, 4, 0],
       [4, 2, 1, ..., 21, 23, 45],
       ...,
       [4, 2, 1, ..., 6, 6, 35],
       [1, 2, 1, ..., 6, 15, 15],
       [6, 2, 1, ..., 15, 14, 20]], dtype=object)

# Feature Scaling..!!

In [ ]:
from sklearn.preprocessing import StandardScaler
Scalar=StandardScaler()
X_train=Scalar.fit_transform(X_train)



In [ ]:
X_test=Scaler.fit_transform(X_test)




In [ ]:
# applying similar operation on the Y labels
Y_train = Y_train.reshape((len(Y_train), 1)) 
Y_train = sc_X.fit_transform(Y_train)
Y_train = Y_train.ravel()
Y_train

In [ ]:
We have our training and test data sets seperated which can be used to build a machine learning model now